### ISSUE TITLE
mod in yuzu

### ISSUE THREAD

**Issue by Raymond-Epitech** [CraftyBoss/SuperMarioOdysseyOnline#12]
The problem is that the mod does'nt ask for an ip when it is launched. Consequently, you cant play multiplayer...

**Comment by KeiBoogie** [comment]
Same, pls fix!!!

**Comment by Sanae6** [comment]
This is not an issue that we can solve ourselves, the cause is on Yuzu's end. If you're going to ask for it to be fixed, ask the Yuzu devs instead.
