### ISSUE TITLE
Another Wooded Kingdom Crash

### ISSUE THREAD

**Issue by GamesJam82** [CraftyBoss/SuperMarioOdysseyOnline#15]
If you try going to Wooded Kingdom it sometimes crashes. [Crash Log](https://github.com/CraftyBoss/SuperMarioOdysseyOnline/files/8988535/01687836751_0100000000010000.log)

**Comment by GamesJam82** [comment]
Apparently if the maxplayers is over 7 then Wooded crashes.

**Comment by Fuzzy2319** [comment]
duplicate of #4

**Comment by speyejack** [comment]
Closed as duplicate
