### ISSUE TITLE
Connecting to server but it never does 

### ISSUE THREAD

**Issue by darkblood159** [CraftyBoss/SuperMarioOdysseyOnline#18]
Hey so on one switch I have firmware 13.2.0 and it connects with no problem. And on my second switch it is on firmware 14.1.2 it refuses to connect and instead stalls on the "connecting to server" message. Any way to fix this?

**Comment by Crazalu** [comment]
Wrong IP (or port) or no internet

**Comment by speyejack** [comment]
Please check the [site](https://smoo.it) for troubleshooting. If you still need help troubleshooting, please ask nicely on the discord.
