### ISSUE TITLE
[Bug] Wrong CapPacket.CapAnim content 

### ISSUE THREAD

**Issue by JulesGuesnon** [CraftyBoss/SuperMarioOdysseyOnline#24]
# Description

Hey! So sometimes when you throw your cap, the mod will send an invalid ut8 sequence of bytes for the CapAnim. Here are some examples: 

```
Bytes: 
105, 110, 103, 87, 97, 105, 116, 82, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 63
Decoded string:
yR�?
```

```
Bytes:
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 63
Decoded string:
�?
```

# Fix idea

The only thing I could understand is that the issue is coming from [here](https://github.com/CraftyBoss/SuperMarioOdysseyOnline/blob/b71a6fc27bb79e2f8b68533e72fdb3b9bc18f147/source/server/Client.cpp#L484) but I have no idea how `al::getActionName` works

**Comment by speyejack** [comment]
Has this been tried on the latest dev version?

**Comment by speyejack** [comment]
If you can reproduce this, please leave a comment and I'll reopen this.
