### ISSUE TITLE
where do i put the apmosphere folder in ryujinx or yuzu to play smo online

### ISSUE THREAD

**Issue by dF-Ex** [CraftyBoss/SuperMarioOdysseyOnline#25]
hello i got the build but i wanted to play on yuzu or ryujinx with smo, how do i do it

**Comment by Istador** [comment]
Ryujinx:
- File -> Open Ryujinx Folder -> sdcard
- Should be at `C:\Users\YOUR_USER_NAME\AppData\Roaming\Ryujinx\sdcard\atmosphere`

Yuzu:
- File -> Open yuzu Folder -> sdmc
- Should be at `C:\Users\YOUR_USER_NAME\AppData\Roaming\yuzu\sdmc\atmosphere`

**Comment by Sanae6** [comment]
Assuming the issue has been resolved, I am closing this. If you need further help, go and ask in [the Discord server](https://discord.gg/jYCueK2BqD).
