### ISSUE TITLE
how do i build smo online

### ISSUE THREAD

**Issue by mightymariomanlol** [CraftyBoss/SuperMarioOdysseyOnline#27]
just a simple question, how do i build smo online, do i need requirments or something, if u do know how please let me know thx

**Comment by Istador** [comment]
See the [readme](https://github.com/CraftyBoss/SuperMarioOdysseyOnline/blob/b71a6fc27bb79e2f8b68533e72fdb3b9bc18f147/README.md#building-prerequisites).

**Comment by Sanae6** [comment]
Assuming this has been resolved.
