### ISSUE TITLE
When a Switch Player Stops Moving, PC Players Emulator (Ryujinx) Stops until the Switch Player Moves Again

### ISSUE THREAD

**Issue by Framerr** [CraftyBoss/SuperMarioOdysseyOnline#3]
I tried connecting without the switch player connected, and now, the game takes so much time to load, and do not let me play when it loads, im stopped until another switch player connects and moves (sometimes, only having the switch player connected works, but if he moves and stops again, we have the main problem).

I tried restarting the server and changing options in ryujinx in the section system and the section multiplayer, but i cannot make it to work properly.

**Comment by Framerr** [comment]
This is my log (i connect with the Switch player connected, then the switch player disconnects and my game freezes, then i closed the emulator with Alt+F4)

[Ryujinx_1.0.0-ldn2.4_2022-06-21_03-20-24.log](https://github.com/CraftyBoss/SuperMarioOdysseyOnline/files/8945014/Ryujinx_1.0.0-ldn2.4_2022-06-21_03-20-24.log)

**Comment by Arionic** [comment]
It happens on stable release too, with ryujinx it doesn't load the stage, and with a switch player joined it loads in ryujinx, but the switch player needs to be moving for the ryujinx player to move, if it freeze, when the switch player moves all works again, weird.

LOG :
[Ryujinx_1.1.151_2022-06-21_03-45-19.log](https://github.com/CraftyBoss/SuperMarioOdysseyOnline/files/8945208/Ryujinx_1.1.151_2022-06-21_03-45-19.log)

**Comment by riperiperi** [comment]
This sounds like an issue caused by Ryu only having one thread for BSD. Most games use non-blocking sockets on switch, but this mod seems to block on receive, which means that it can't do anything else socket related until that returns (when it gets data, or when the socket closes).

You need to revert this PR to overcome the limit... Though it is only a workaround that adds one other thread, and may cause crashes depending on how the service is used.
https://github.com/Ryujinx/Ryujinx/pull/3394

**Comment by Arionic** [comment]
ok, i tried with the workaround that you sugested and it does nothing, the bugs and freezes are persistent like before

**Comment by riperiperi** [comment]
Did you _revert_ the linked PR, build the emulator yourself? I wasn't getting this issue with ryu<->ryu, which would likely be in an even worse situation with freezing.

**Comment by Arionic** [comment]
oh, i didn't build the emulator, gonna try that.

**Comment by Framerr** [comment]
> Did you _revert_ the linked PR, build the emulator yourself? I wasn't getting this issue with ryu<->ryu, which would likely be in an even worse situation with freezing.

Can you share your working build pls?

**Comment by Niwu34** [comment]
I was able to get  a Server running with 2 Emu instances running (No switch)
Prs Being used: Vulkan + #3405 + #3394 reverted
![unknown](https://user-images.githubusercontent.com/67392333/174896268-8362186f-6f6c-4bb4-be88-d89fef7110fa.png)

**Comment by Framerr** [comment]
Ok, i did it, and it works fine, so im gonna close this issue.

You can download it at this link: (Link to a Discord message at the Mod Server, if it not works, join the mod server and try again)
https://discord.com/channels/481991664085499924/481993523424395297/988989882351357952

**Comment by parkers0405** [comment]
Hey could I get the build? The discord link is not working for me

**Comment by Sanae6** [comment]
@parkers0405 https://discord.gg/jYCueK2BqD join the discord and then use the link.
