### ISSUE TITLE
I’ve tried to join my server multiple times but the ip always fails

### ISSUE THREAD

**Issue by SomeoneIDKK** [CraftyBoss/SuperMarioOdysseyOnline#31]
Every time I want to join my server, it says that it failed. For example, my ip is 0.0.0.0:1027. When I join in Switch, I can’t use the “:” sign, so what do I put? And when I join in Ryujinx, when I put the whole ip (0.0.0.0:1027), it says that it failed. What do I do?

**Comment by Istador** [comment]
[`0.0.0.0`](https://en.wikipedia.org/wiki/0.0.0.0) is an invalid IP address.

Use [`127.0.0.1`](https://en.wikipedia.org/wiki/Localhost) to connect to the server on the same computer.

[FAQ: What is a public/private IPv4 address?](https://smoo.it/#/faq/107)

---

If you're using a mod version recommended for Ryujinx (not `1.0.0`, but rather a `dev` branch [build](https://github.com/CraftyBoss/SuperMarioOdysseyOnline/actions/workflows/build.yml?query=branch%3Adev)), it should ask for the port in a separate dialog. With version `1.0.0` of the mod you're currently limited to the default `1027` port and can't change it.

An option to enter the port as `:1027` together with the IP would be a nice new feature though.

**Comment by SomeoneIDKK** [comment]
When I tried the ip 127.0.0.1 on my pc, it said that it Failed to Connect. Do I change the ip in settings.JSON?



Also, What about console?

Edit: How do I remove the ip that I placed on my switch? I accidentally used the wrong one and I can’t remove it. I’ve tried everything

**Comment by Istador** [comment]
> When I tried the ip 127.0.0.1 on my pc, it said that it Failed to Connect. Do I change the ip in settings.JSON?

No, you leave the IP in the `settings.json` at the default `0.0.0.0`.
Remember that you need to enable guest internet access in the Ryujinx settings and you need to change the default user profile.

> Also, What about console?

Sorry, I overread that you were using/trying both, console and emu.

On the Switch you need to enter the private IPv4 address of your PC (that is running the server). You can find it in the network adapter settings or by using `ipconfig` on the cli/cmd.

> Edit: How do I remove the ip that I placed on my switch? I accidentally used the wrong one and I can’t remove it. I’ve tried everything

[FAQ: How do I change the server I'm connected to?](https://smoo.it/#/faq/102)
