### ISSUE TITLE
Wooded Kingdom Crash

### ISSUE THREAD

**Issue by Saria101** [CraftyBoss/SuperMarioOdysseyOnline#4]
After the Cutscene for Defeating Spewart, a white screen appears and then the game crashes. After loading the save, you crash immediately.

**Comment by Saria101** [comment]
[Crash Log](https://pastebin.com/WsDRzyyF)

**Comment by GRAnimated** [comment]
edited your comment to move the entire crash log off of github- way too long here

**Comment by GamesJam82** [comment]
I found out that if the maxplayers is over 7 then this crash happens.

**Comment by speyejack** [comment]
This probably came from spawning too many actors to capture. However, i dont think this is an issue anymore, but if it is on the latest dev, someone please comment and I'll reopen this.
