### ISSUE TITLE
Cannot join servers

### ISSUE THREAD

**Issue by IrenvanderBeekPXL** [CraftyBoss/SuperMarioOdysseyOnline#42]
Hello

I am trying to join a localhosted server (127.0.0.1) with an uncompleted save file I get an infinite loading screen (new file) or a black screen (pre odyssey file). This also happens when trying to join a public server like 51.178.136.142. I'm using Yuzu if that matters and so see myself joining in the server logs on the localhosted server.

Thanks :)

**Comment by Istador** [comment]
https://smoo.it/#/play/yuzu
Short: use the latest dev build.

**Comment by IrenvanderBeekPXL** [comment]
Okay thanks, gonna try that

**Comment by speyejack** [comment]
Please check the [site](https://smoo.it) for troubleshooting. If you still need help troubleshooting, please ask nicely on the discord.
