### ISSUE TITLE
Freeze after a few minutes

### ISSUE THREAD

**Issue by flo-lec** [CraftyBoss/SuperMarioOdysseyOnline#45]
Hey, I don't know what's happening but for no reason, I'm totally frozen after a few minutes
Is that because of my way of setting up my server or anything else?
![image](https://user-images.githubusercontent.com/59474408/202230828-49af23ba-441c-4fc0-909f-abe4248f3b10.png)

**Comment by Crazalu** [comment]
One of many things can be happening here, its yuzu bugging, it is something about the game, something about the file, or you have something else installed along with it.

**Comment by GamesJam82** [comment]
This also happens to me on switch sometimes

**Comment by speyejack** [comment]
Please check the [site](https://smoo.it) for troubleshooting. If you still need help troubleshooting, please ask nicely on the discord.

If this does persist, we need steps to reproduce the issue or at least a log file.
