### ISSUE TITLE
Infinite black screen while starting a game save

### ISSUE THREAD

**Issue by Nay-on** [CraftyBoss/SuperMarioOdysseyOnline#46]
When I'm connected on my server and load a save file, a (loading ?) black screen apear and never disapear. Any Idea ?
I'm on SMO 1.0.0 on Yuzu

**Comment by Istador** [comment]
What version of this mod do you use?

SMOO 1.0.0 doesn't support emulators at all.
For yuzu you'll need the latest dev build for emulators.
https://github.com/CraftyBoss/SuperMarioOdysseyOnline/releases/tag/latest-dev

Also see the following guide for additional yuzu specific instructions and configuration: https://smoo.it/#/play/yuzu

**Comment by Nay-on** [comment]
Following the step on https://smoo.it/#/play/yuzu solve my issue, I don't extract on right path certains files
