### ISSUE TITLE
It's just not working

### ISSUE THREAD

**Issue by TheMonfunk** [CraftyBoss/SuperMarioOdysseyOnline#48]
i installed the mod and it has the new title of "SMOO" but nothing is changed and the mod won't let me pull up menus or put in server IDs. Im in 1.0.0

**Comment by qwertzuiii** [comment]
then you installed it wrong or somthing got corrupted. Try to unpack it again or check, if you installed the mod correctly. For me it works fine with both this version and the freezetag version

**Comment by speyejack** [comment]
Please check the [site](https://smoo.it) for troubleshooting. If you still need help troubleshooting, please ask nicely on the discord.
