### ISSUE TITLE
When I launch the game no ip is asked

### ISSUE THREAD

**Issue by mithrandir63** [CraftyBoss/SuperMarioOdysseyOnline#50]
Pls Help the mod is aleadry in my game and in the menu the of the game is change. Pls Help

**Comment by mithrandir63** [comment]
My Game is not in 1.0.0

**Comment by Istador** [comment]
> My Game is not in 1.0.0

Version `1.0.0` of the game is an absolut requirement for the mod. Without it it will not work.

If you're playing on the Nintendo Switch, then downgrade the game as described here: https://smoo.it/#/play/switch

If you're playing on an emulator, then dump the base game without the update(s) from your Nintendo Switch: https://smoo.it/#/faq/104
