### ISSUE TITLE
Player names showing up above players heads - how to turn this off?

### ISSUE THREAD

**Issue by djw1023** [CraftyBoss/SuperMarioOdysseyOnline#51]
Hi! I've just gotten the mod working (which is awesome!) and I'm seeing player names above the heads of other players.  This is great to see that it's all working, but if playing hide-and-seek, it kindof gives away location.  Is there a way to disable this? 

Also, in the description of the mod there seem to be different roles for different players (hider/seeker), auto-kills (if players get close enough), timers, etc - some of which are tied to the d-pad. None of that seems to work for me.  Is this built? If so how do I enable / disable it?

**Comment by Istador** [comment]
Seeing player names is dependant on the Hide & Seek status.
Without enabling Hide & Seek player names of everyone will be shown.

[Controls](https://smoo.it/#/faq/101):
- L + D-Pad Left - Enable/disable Hide & Seek [H&S]
- [H&S] D-Pad Up - Switch between hider and seeker
- [H&S] [Hider] D-Pad Left - Decrease hiding time
- [H&S] [Hider] D-Pad Right - Increase hiding time
- [H&S] [Hider] L + D-Pad Down - Reset hiding time
- [H&S] [Gravity] L + D-Pad Right - Toggle gravity camera

**Comment by djw1023** [comment]
Brilliant, thanks! That works.

It may be a good idea to add this explanation to the Gamemode Info section of the readme -- the readme currently has the commands about increasing/decreasing hiding time, but doesn't say how to enable and disable hide and seek and switch between hider and seeker, which would make it easier to get it going.

**Comment by speyejack** [comment]
Should be closed by #56

**Comment by speyejack** [comment]
I'm going to close this as the actual issue has been solved
