### ISSUE TITLE
NDC Band Members Sync Issue

### ISSUE THREAD

**Issue by Saria101** [CraftyBoss/SuperMarioOdysseyOnline#6]
If different players get the different band members, Pauline will not initiate the next story sequence despite all 4 members being in the NDC Hall and not being in the city outside.

**Comment by Crazalu** [comment]
This is easily fixable, if any band member isn’t synchronized with yours, just talk to Pauline a bunch, it skips ahead the story until you have sewers (you need to talk to Pauline a lot of you only have 1 musician though)

**Comment by speyejack** [comment]
If that solution didnt work, please leave a comment and ill reopen this.
