### ISSUE TITLE
Every Outfit Unlocks

### ISSUE THREAD

**Issue by Saria101** [CraftyBoss/SuperMarioOdysseyOnline#8]
Every Outfit in the game appears in our inventory despite never buying any of them.

**Comment by ecumber** [comment]
While I can't speak on behalf for the devs, I assume this is a deliberate decision because there is code that hooks into the game to unlock every costume. This is probably just so you can choose your own costume from the beginning to help with distinguishing between other players.

**Comment by speyejack** [comment]
ecumber is right. This makes hide and seek easier as anyone can choose their outfit.
