### ISSUE TITLE
Luncheon Story Syncing Problem

### ISSUE THREAD

**Issue by Saria101** [CraftyBoss/SuperMarioOdysseyOnline#9]
Other player had completed the story and got the moon rock in Luncheon kingdom but I had to beat the cockatiel fight again.

**Comment by Crazalu** [comment]
The game doesn't autosave when someone else gets a moon, you can't be in a subarea when a multimoon is grabbed (you can leave shortly after and die and it will be fine but it only works half the time)

**Comment by speyejack** [comment]
I believe this is a server issue not syncing all players. However, for the most part completion to be done together to prevent any issues. 

If there are any more issues please leave a comment and ill open this back up.
